services:
  app:
      build: .
      ports: 
      - 3000:3000
      volumes:
      - .:/home/node/app

  db:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: nest
        MYSQL_ROOT_PASSWORD: root
      ports: 
        - 33066:3306  
      volumes:
        - ./.docker/mysql:/docker-entrypoint-initdb.d